version: '3.8'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
      target: production
    ports:
      - "3001:3000"
    env_file:
      - .env
    volumes:
      - ./server/data:/app/data
    restart: unless-stopped
    depends_on:
      - mongo

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      target: production
    ports:
      - "3000:3000"
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - server

  mongo:
    image: mongo:6
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}

volumes:
  mongo-data:

# Docker Compose will automatically use variables from .env file
# All environment variables are defined in the .env file at the root level
# The project includes a .env.example file that can be copied to .env

networks:
  default:
    driver: bridge